# Generated by Django 4.0.4 on 2022-05-29 03:39

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.EmailField(default=None, max_length=122)),
                ('message', models.TextField(default=None)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', tinymce.models.HTMLField()),
                ('url', models.CharField(max_length=50)),
                ('featured', models.BooleanField(null=True)),
                ('add_date', models.DateTimeField(auto_now=True, null=True)),
                ('image', models.ImageField(upload_to='post/')),
            ],
        ),
    ]
